import { SP } from './species.tsx';

export type ImageType = {
  speciesId: string;
  title: string;
  url: string;
  authorId?: number;
  place?: string;
  description?: string;
};

// Used this to display a specific image as anwser!
// Update quiz.ts to add the corresponding imageId
export const answerImages: { [key: string]: ImageType } = {};

// Images used for question
export const images: Array<ImageType> = [
  {
    speciesId: SP.MB,
    title: 'Murin de Bechstein',
    url: './assets/img/species/P1020489.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/P1040842.JPG',
    authorId: 2,
    place: 'Otré',
    description: undefined,
  },
  {
    speciesId: SP.Rh,
    title: 'Petit rhinolophe',
    url: './assets/img/species/DSC04546.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.Barbar,
    title: 'Barbastelle',
    url: 'https://plecotus.natagora.be/fileadmin/_processed_/b/9/csm_BarbastellaBarbastellus_JeanLouisGathoye__10__162fa6628a.jpg',
    authorId: 3,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.Pleaus,
    title: 'Oreillard gris',
    url: './assets/img/species/DSC_9374.JPG',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/110302 006.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/20110424 002.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/DSC07137.JPG',
    authorId: 2,
    place: 'Hastière',
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/DSC07167.JPG',
    authorId: 2,
    place: 'Han-sur-Lesse',
    description: undefined,
  },
  {
    speciesId: SP.Mmba,
    title: 'Murin à moustaches',
    url: './assets/img/species/P1040808.JPG',
    authorId: 2,
    place: 'Montaigle',
    description: undefined,
  },
  {
    speciesId: SP.Rf,
    title: 'Grand rhinolophe',
    url: './assets/img/species/P1040812.JPG',
    authorId: 2,
    place: 'Durnal',
    description: undefined,
  },
  {
    speciesId: SP.Md,
    title: 'Murin de Daubenton',
    url: './assets/img/species/P1010182.JPG',
    authorId: 2,
    place: 'Hotton',
    description: undefined,
  },
  {
    speciesId: SP.Mn,
    title: 'Murin de Natterer',
    url: './assets/img/species/P1020544.JPG',
    authorId: 2,
    place: 'Hotton',
    description: undefined,
  },
  {
    speciesId: SP.MD,
    title: 'Murin des marais',
    url: './assets/img/species/DSC_2031.JPG',
    authorId: 2,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.MD,
    title: 'Murin des marais',
    url: './assets/img/species/IMAGE_17.jpg',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.MB,
    title: 'Murin de Bechstein',
    url: './assets/img/species/DSC_6718.jpg',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.Pleaur,
    title: 'Oreillard roux',
    url: './assets/img/species/20110131 010.JPG',
    authorId: 2,
    place: 'Briscol',
    description: undefined,
  },
  {
    speciesId: SP.ME,
    title: 'Murins à oreilles échancrées',
    url: './assets/img/species/DSC_6648.jpg',
    authorId: 2,
    place: 'La Malonne, Cuesmes',
    description: undefined,
  },
  {
    speciesId: SP.Eptser,
    title: 'Sérotine commune',
    url: './assets/img/species/DSC09710c.jpg',
    authorId: 2,
    place: 'Purnode',
    description: undefined,
  },
  {
    speciesId: SP.Rf,
    title: 'Grand Rhinolophe',
    url: './assets/img/species/20240204-plecotus-2.jpg',
    authorId: 1,
    place: 'Florenville',
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/DSC_1379.jpg',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/DSC_6640.jpg',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/DSC03215_1.JPG',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/DSC03323_1.JPG',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/P1010053.JPG',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'Grand Murin',
    url: './assets/img/species/tR5_JvCV.jpeg',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.Barbar,
    title: "Barbastelle d'Europe",
    url: './assets/img/species/DSC06717c.jpg',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.Pleaur,
    title: 'Oreillard roux',
    url: './assets/img/species/DSC06762.JPG',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.Pleaur,
    title: 'Oreillard roux',
    url: './assets/img/species/DSC06770.JPG',
    authorId: 2,
    place: undefined,
    description: undefined,
  },
  {
    speciesId: SP.MB,
    title: 'Murin de Bechstein',
    url: './assets/img/species/DSC02969.JPG',
    authorId: 2,
    place: 'Han-sur-Lesse',
    description: undefined,
  },
  {
    speciesId: SP.Mmba,
    title: 'Murin de Brandt',
    url: './assets/img/species/DSC02957.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.Rf,
    title: 'Grand Rhino',
    url: './assets/img/species/DSC02910c.JPG',
    authorId: 2,
    place: 'Freyr',
    description: undefined,
  },
  {
    speciesId: SP.Md,
    title: 'Murin de Daubenton',
    url: './assets/img/species/DSC02905c.JPG',
    authorId: 2,
    place: 'Yvoir',
    description: undefined,
  },
  {
    speciesId: SP.Rh,
    title: 'Petit Rhino',
    url: './assets/img/species/DSC01304.JPG',
    authorId: 2,
    place: 'Han-sur-Lesse',
    description: undefined,
  },
  {
    speciesId: SP.Mmba,
    title: 'Mmba',
    url: './assets/img/species/DSC09937.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.Rh,
    title: 'Petit Rhino',
    url: './assets/img/species/DSC09759.JPG',
    authorId: 2,
    place: 'Géromont',
    description: undefined,
  },
  {
    speciesId: SP.Pipsp,
    title: 'Pipistrelle',
    url: './assets/img/species/DSC09711c.jpg',
    authorId: 2,
    place: 'Purnode',
    description: undefined,
  },
  {
    speciesId: SP.Pleaur,
    title: 'Oreillard roux',
    url: './assets/img/species/DSC09257.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.ME,
    title: 'Murins à oreilles échancrées',
    url: './assets/img/species/DSC08441.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.Pleaus,
    title: 'Oreillard gris',
    url: './assets/img/species/DSC08326.JPG',
    authorId: 2,
    place: 'Lessive',
    description: undefined,
  },
  {
    speciesId: SP.ME,
    title: 'Murins à oreilles échancrées',
    url: './assets/img/species/DSC07416c.jpg',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.Rh,
    title: 'Petit Rhino',
    url: './assets/img/species/DSC07179c.jpg',
    authorId: 2,
    place: 'Grune',
    description: undefined,
  },
  {
    speciesId: SP.ME,
    title: 'ME',
    url: './assets/img/species/DSC07131c.jpg',
    authorId: 2,
    place: 'Hastière',
    description: undefined,
  },
  {
    speciesId: SP.Mmba,
    title: 'Murin de Brandt',
    url: './assets/img/species/DSC07084c.jpg',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.MB,
    title: 'MB',
    url: './assets/img/species/DSC07070c.jpg',
    authorId: 2,
    place: 'Pont-à-Lesse',
    description: undefined,
  },
  {
    speciesId: SP.Md,
    title: 'Md',
    url: './assets/img/species/DSC07067c.jpg',
    authorId: 2,
    place: 'Pont-à-Lesse',
    description: undefined,
  },
  {
    speciesId: SP.ME,
    title: 'ME',
    url: './assets/img/species/DSC06772.JPG',
    authorId: 2,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.Pleaur,
    title: 'Pleaur',
    url: './assets/img/species/DSC06770_1.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.Mn,
    title: 'Mn',
    url: './assets/img/species/DSC03479_1.JPG',
    authorId: 2,
    place: 'Wavre',
    description: undefined,
  },
  {
    speciesId: SP.Mmba,
    title: 'Mmba',
    url: './assets/img/species/DSC03310_1.JPG',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.Mn,
    title: 'Mn',
    url: './assets/img/species/DSC02857_1.JPG',
    authorId: 2,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.MD,
    title: 'MD',
    url: './assets/img/species/DSC02852.JPG',
    authorId: 2,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.Pleaus,
    title: 'Pleaus',
    url: './assets/img/species/DSC_2226.NEF.jpg',
    authorId: 2,
    place: 'Villers-devant-Orval',
    description: undefined,
  },
  {
    speciesId: SP.Eptser,
    title: 'Serotine',
    url: './assets/img/species/DSC_2225.NEF.jpg',
    authorId: 2,
    place: 'Villers-devant-Orval',
    description: undefined,
  },
  {
    speciesId: SP.Mn,
    title: 'Mn',
    url: './assets/img/species/DSC_1077.jpg',
    authorId: 2,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.Md,
    title: 'Md',
    url: './assets/img/species/DSC_7944.jpg',
    authorId: 2,
    place: 'Nettine',
    description: undefined,
  },
  {
    speciesId: SP.MB,
    title: 'MB',
    url: './assets/img/species/DSC_6718_1.jpg',
    authorId: 2,
    place: 'Rochefort',
    description: undefined,
  },
  {
    speciesId: SP.MD,
    title: 'MD',
    url: './assets/img/species/DSC_6632.jpg',
    authorId: 2,
    place: 'La Malonne',
    description: undefined,
  },
  {
    speciesId: SP.ME,
    title: 'ME',
    url: './assets/img/species/DSC_6645.jpg',
    authorId: 2,
    place: 'La Malonne',
    description: undefined,
  },
  {
    speciesId: SP.MD,
    title: 'MD',
    url: './assets/img/species/DSC_2031_1.JPG',
    authorId: 2,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.MB,
    title: 'MB',
    url: './assets/img/species/DSC_2045.JPG',
    authorId: 2,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.Barbar,
    title: 'Barbar',
    url: './assets/img/species/P1060249.JPG',
    authorId: 2,
    place: 'Luxembourg',
    description: undefined,
  },
  {
    speciesId: SP.Pipsp,
    title: 'Pipsp',
    url: './assets/img/species/20110131_001.JPG',
    authorId: 2,
    place: 'Hour',
    description: undefined,
  },
  {
    speciesId: SP.Eptser,
    title: 'Eptser',
    url: './assets/img/species/DSCN4975.JPG',
    authorId: 2,
    place: 'Furfooz',
    description: undefined,
  },
  {
    speciesId: SP.ME,
    title: 'ME',
    url: './assets/img/species/P1020507.JPG',
    authorId: 2,
    place: 'Hastière',
    description: undefined,
  },
  {
    speciesId: SP.Mn,
    title: 'Mn',
    url: './assets/img/species/P1020450.JPG',
    authorId: 2,
    place: 'Denée',
    description: undefined,
  },
  {
    speciesId: SP.Mmba,
    title: 'Mmba',
    url: './assets/img/species/P1020445.JPG',
    authorId: 2,
    place: 'Denée',
    description: undefined,
  },
  {
    speciesId: SP.Md,
    title: 'Md',
    url: './assets/img/species/P1010220.JPG',
    authorId: 2,
    place: 'Hotton',
    description: undefined,
  },
  {
    speciesId: SP.Eptser,
    title: 'Eptser',
    url: './assets/img/species/P1010197.JPG',
    authorId: 2,
    place: 'Hotton',
    description: undefined,
  },
  {
    speciesId: SP.MD,
    title: 'MD',
    url: './assets/img/species/P1040857.JPG',
    authorId: 2,
    place: 'Challeux',
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'MM',
    url: './assets/img/species/20240106-Plecotus-30.jpg',
    authorId: 1,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.MM,
    title: 'MM',
    url: './assets/img/species/20240106-Plecotus-36.jpg',
    authorId: 1,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.Pleaur,
    title: 'Pleaur',
    url: './assets/img/species/20240113-Plecotus-11.jpg',
    authorId: 1,
    place: 'Lanaye',
    description: undefined,
  },
  {
    speciesId: SP.Pleaur,
    title: 'Pleaur',
    url: './assets/img/species/20240121-plecotus-04.jpg',
    authorId: 1,
    place: 'Villers-la-Ville',
    description: undefined,
  },
  {
    speciesId: SP.Mmba,
    title: 'Mmba',
    url: './assets/img/species/20240121-plecotus-08.jpg',
    authorId: 1,
    place: 'Villers-la-Ville',
    description: undefined,
  },
  {
    speciesId: SP.Eptser,
    title: 'Eptser',
    url: './assets/img/species/20240121-plecotus-10.jpg',
    authorId: 1,
    place: 'Villers-la-Ville',
    description: undefined,
  },
];

type AuthorType = {
  name: string;
  firstname: string;
  mail?: string;
  url?: string;
};

export const authors: { [key: number]: AuthorType } = {
  1: {
    name: 'Lebon',
    firstname: 'Lionel',
    mail: undefined,
    url: 'https://www.instagram.com/lebolnobel/',
  },
  2: {
    name: 'Smits',
    firstname: 'Quentin',
    mail: undefined,
    url: 'https://photos.google.com/share/AF1QipNJ-gMv6hbSQcTJHKhY-Xx8DEtVAA6Ir95CF412tZEUmWz6J-JjYqm4xc2Vnp8Nyg?key=QW53X0dFbkpQLWZSdjVGcDRZb0RjQ3ZPSTFoV2xR',
  },
  3: {
    name: 'Gathoye',
    firstname: 'Jean-louis',
    mail: undefined,
    url: undefined,
  },
};
